plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	exclusiveContent {
		forRepository {
			maven {
				url 'https://jitpack.io'
			}
		}
		filter {
			includeGroup "com.github.ramixin"
		}
	}
	maven {
		name = 'TerraformersMC'
		url = 'https://maven.terraformersmc.com/'
	}
	maven {
		name 'Xander Maven'
		url 'https://maven.isxander.dev/releases'
	}
	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
		content {
			includeGroup "maven.modrinth"
		}
	}
}

def dateFormat = new Date().format("yy.MM.dd")

tasks.register("buildDated") {
	group = "build"
	description = "Assembles project with date in archive filenames"
	dependsOn "build"
}

gradle.taskGraph.whenReady { graph ->
	def dated = graph.hasTask(tasks.buildDated)

	tasks.matching { it.name in ["jar", "sourcesJar"] }.configureEach {
		def prefix = dated ? "${dateFormat}-" : ""
		archiveBaseName.set("${prefix}${archives_base_name}")
		archiveVersion.set("${mod_version}+mc${minecraft_version}")
	}
}

loom {
	accessWidenerPath = file("src/main/resources/enderscape.accesswidener")

	runs {
		client {
			runDir "run"
		}
		server {
			runDir "run_server"
		}
	}
}

fabricApi {
	configureDataGeneration() {
		client = true
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	implementation "com.terraformersmc:modmenu:${project.modmenu_version}"
	implementation "dev.isxander:yet-another-config-lib:${project.yacl_version}"
	implementation "maven.modrinth:mixson:${project.mixson_version}"
	implementation "maven.modrinth:lithostitched:${project.lithostitched_version}"
	include "maven.modrinth:mixson:${project.mixson_version}"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}

	duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	from("LICENSE.md") {
		rename { "LICENSE_enderscape" }
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	repositories {
	}
}