plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	exclusiveContent {
		forRepository {
			maven {
				url 'https://jitpack.io'
			}
		}
		filter {
			includeGroup "com.github.ramixin"
		}
	}
	maven {
		name = 'TerraformersMC'
		url = 'https://maven.terraformersmc.com/'
	}
	maven {
		name 'Xander Maven'
		url 'https://maven.isxander.dev/releases'
	}
	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
		content {
			includeGroup "maven.modrinth"
		}
	}
	// JEI
	maven {
		name = "Jared's maven"
		url = "https://maven.blamejared.com/"
	}
	maven {
		name = "ModMaven"
		url = "https://modmaven.dev"
	}

	// RRV
	maven {
		name = "Cassian's Maven"
		url = uri("https://maven.cassian.cc")
	}
}

def dateFormat = new Date().format("yy.MM.dd")

tasks.register("buildDated") {
	group = "build"
	description = "Assembles project with date in archive filenames"
	dependsOn "build"
}

gradle.taskGraph.whenReady { graph ->
	def dated = graph.hasTask(tasks.buildDated)

	tasks.matching { it.name in ["jar", "sourcesJar"] }.configureEach {
		def prefix = dated ? "${dateFormat}-" : ""
		archiveBaseName.set("${prefix}${archives_base_name}")
		archiveVersion.set("${mod_version}+mc${minecraft_version}")
	}
}

loom {
	accessWidenerPath = file("src/main/resources/enderscape.accesswidener")

	runs {
		client {
			runDir "run"
		}
		server {
			runDir "run_server"
		}
	}

	splitEnvironmentSourceSets()

	mods {
		enderscape {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"

	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	implementation "com.terraformersmc:modmenu:${project.modmenu_version}"
	implementation "dev.isxander:yet-another-config-lib:${project.yacl_version}"

	implementation "maven.modrinth:lithostitched:${project.lithostitched_version}"
	implementation "maven.modrinth:trim-patcher:${project.trim_patcher_version}"

	compileOnly("mezz.jei:jei-26.1.2-common-api:${jei_version}") {
		transitive = false
	}
	compileOnly("mezz.jei:jei-26.1.2-fabric-api:${jei_version}") {
		transitive = false
	}

	compileOnly("cc.cassian.rrv:reliable-recipe-viewer-fabric:${rrv_version}") {
		transitive = false
	}

	switch (project.recipe_viewer) {
		case "rrv" -> runtimeOnly("cc.cassian.rrv:reliable-recipe-viewer-fabric:${rrv_version}")
		case "jei" -> runtimeOnly("mezz.jei:jei-26.1.2-fabric:${jei_version}")
	}
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE.md") {
		rename { "LICENSE_enderscape" }
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	repositories {
	}
}