# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Fabric API
fabric_api_version=0.155.0+26.2
modmenu_version=20.0.0
yacl_version=3.9.5+26.2-fabric
lithostitched_version=1.7.13-fabric-26.2
trim_patcher_version=1.0-mc26.2
jei_version=30.9.0.53
rrv_version=8.5.0+26.2

# rrv, jei or none
recipe_viewer=none

mod_version = 3.0.1

maven_group = net.penumbra.enderscape
archives_base_name = enderscape-fabric

# for updating: https://fabricmc.net/develop/