org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.217
neo_version_range=[21.1.173,)
loader_version_range=[1,)

trimmed_version=3.0.0
lithostitched_version=1.5.2
yacl_version=3.7.1+1.21.1-neoforge
mixson_version=v1.3.2

terrablender_version=4.1.0.8

archives_base_name=enderscape-neoforge
mod_id=enderscape
mod_name=Enderscape
mod_license=MIT
mod_version=2.1.0
mod_group_id=net.bunten.enderscape
mod_authors=lunarbunten, hivye, Konci, Ninni, Orcinus, Luke Bemish
mod_description=Total overhaul of The End with new generation, biomes, mobs, and other features.
