org.gradle.jvmargs=-Xmx1G

minecraft_version=25w33a
yarn_mappings=25w33a+build.8
loader_version=0.17.2
loom_version=1.11-SNAPSHOT

# Fabric API
fabric_version=0.131.3+1.21.9
modmenu_version=15.0.0-beta.3
yacl_version=3.7.1+1.21.9-fabric
mixson_version=f45ce6470a

mod_version = 1.0.9
maven_group = net.bunten.enderscape
archives_base_name = enderscape-fabric

# for updating: https://modmuss50.me/fabric.html