modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile = "assets/enderscape/icon.png"
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''

[[accessTransformers]]
file="accesstransformer.cfg"

[[mixins]]
config="enderscape.mixins.json"

[[mixins]]
config="enderscape.client.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="trimmed"
type="required"
versionRange="[${trimmed_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId = "yet_another_config_lib_v3"
type="required"
versionRange="[${yacl_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId="terrablender"
type="optional"
versionRange="[${terrablender_version},)"
ordering="NONE"
side="BOTH"
