package net.bunten.enderscape.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.BlockTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.block.Block;

import java.util.concurrent.CompletableFuture;

import static net.bunten.enderscape.registry.EnderscapeBlocks.*;
import static net.bunten.enderscape.registry.tag.EnderscapeBlockTags.*;
import static net.fabricmc.fabric.api.tag.convention.v2.ConventionalBlockTags.*;
import static net.minecraft.world.level.block.Blocks.*;

public class EnderscapeBlockTagProvider extends FabricTagProvider<Block> {

    public EnderscapeBlockTagProvider(FabricDataOutput output, CompletableFuture<HolderLookup.Provider> future) {
        super(output, Registries.BLOCK, future);
    }

    @Override
    protected void addTags(HolderLookup.Provider lookup) {
        getOrCreateTagBuilder(BLOCKS_ALLURING_MAGNIA_SPROUTS).add(REPULSIVE_MAGNIA, ETCHED_REPULSIVE_MAGNIA);
        getOrCreateTagBuilder(BLOCKS_REPULSIVE_MAGNIA_SPROUTS).add(ALLURING_MAGNIA, ETCHED_ALLURING_MAGNIA);
        getOrCreateTagBuilder(CELESTIAL_BRICK_BLOCKS).add(CELESTIAL_BRICKS, CELESTIAL_BRICK_SLAB, CELESTIAL_BRICK_STAIRS, CELESTIAL_BRICK_WALL);
        getOrCreateTagBuilder(CELESTIAL_CHANTERELLE_MATURES_ON).add(CELESTIAL_OVERGROWTH);
        getOrCreateTagBuilder(CELESTIAL_CORRUPTS_ON).add(CORRUPT_OVERGROWTH);
        getOrCreateTagBuilder(CELESTIAL_GROVE_VEGETATION_PLANTABLE_ON).forceAddTag(OVERGROWTH_BLOCKS).forceAddTag(BlockTags.DIRT).add(END_STONE, MIRESTONE, VEILED_END_STONE);
        getOrCreateTagBuilder(CELESTIAL_STEMS).add(CELESTIAL_STEM, STRIPPED_CELESTIAL_STEM, CELESTIAL_HYPHAE, STRIPPED_CELESTIAL_HYPHAE);
        getOrCreateTagBuilder(CELESTIAL_WOOD).forceAddTag(CELESTIAL_STEMS).add(CELESTIAL_PLANKS, CELESTIAL_SLAB, CELESTIAL_STAIRS, CELESTIAL_FENCE, CELESTIAL_FENCE_GATE, CELESTIAL_BUTTON, CELESTIAL_SIGN, CELESTIAL_HANGING_SIGN, CELESTIAL_WALL_SIGN, CELESTIAL_WALL_HANGING_SIGN);
        getOrCreateTagBuilder(CHORUS_VEGETATION_PLANTABLE_ON).add(END_STONE, VEILED_END_STONE, CELESTIAL_OVERGROWTH);
        getOrCreateTagBuilder(CORRUPTION_PURIFIES_ON);
        getOrCreateTagBuilder(CORRUPT_BARRENS_VEGETATION_PLANTABLE_ON).forceAddTag(OVERGROWTH_BLOCKS).forceAddTag(BlockTags.DIRT).add(END_STONE, MIRESTONE, VEILED_END_STONE);
        getOrCreateTagBuilder(DRY_END_GROWTH_PLANTABLE_ON).add(END_STONE, VEILED_END_STONE, CELESTIAL_OVERGROWTH);
        getOrCreateTagBuilder(DUSK_PURPUR_BLOCKS).add(DUSK_PURPUR_BLOCK, DUSK_PURPUR_PILLAR, DUSK_PURPUR_STAIRS, DUSK_PURPUR_SLAB, DUSK_PURPUR_WALL, CHISELED_DUSK_PURPUR);
        getOrCreateTagBuilder(ENDERMITE_SAFE_WHEN_NEARBY).add(CORRUPT_OVERGROWTH, CORRUPT_PATH_BLOCK, CORRUPT_GROWTH, POTTED_CORRUPT_GROWTH);
        getOrCreateTagBuilder(END_ORE_BLOCKS).add(NEBULITE_ORE, SHADOLINE_ORE, MIRESTONE_NEBULITE_ORE, MIRESTONE_SHADOLINE_ORE);
        getOrCreateTagBuilder(ETCHED_MAGNIA_BLOCKS).add(ETCHED_ALLURING_MAGNIA, ETCHED_REPULSIVE_MAGNIA);
        getOrCreateTagBuilder(FLANGER_BERRY_VINE_PLANTABLE_ON).forceAddTag(CHANTERELLE_CAP_BLOCKS);
        getOrCreateTagBuilder(FLANGER_BERRY_VINE_SUPPORTS).add(FLANGER_BERRY_FLOWER, UNRIPE_FLANGER_BERRY_BLOCK, RIPE_FLANGER_BERRY_BLOCK);
        getOrCreateTagBuilder(KURODITE_BLOCKS).add(CHISELED_KURODITE, POLISHED_KURODITE_BUTTON, POLISHED_KURODITE_PRESSURE_PLATE);
        getOrCreateTagBuilder(KURODITE_BLOCKS).add(KURODITE, KURODITE_SLAB, KURODITE_STAIRS, KURODITE_WALL);
        getOrCreateTagBuilder(KURODITE_BLOCKS).add(KURODITE_BRICKS, KURODITE_BRICK_SLAB, KURODITE_BRICK_STAIRS, KURODITE_BRICK_WALL);
        getOrCreateTagBuilder(KURODITE_BLOCKS).add(POLISHED_KURODITE, POLISHED_KURODITE_SLAB, POLISHED_KURODITE_STAIRS, POLISHED_KURODITE_WALL);
        getOrCreateTagBuilder(MAGNIA_ARCH_REPLACEABLE).add(END_STONE, MIRESTONE, ALLURING_MAGNIA);
        getOrCreateTagBuilder(MAGNIA_BLOCKS).add(ALLURING_MAGNIA, REPULSIVE_MAGNIA);
        getOrCreateTagBuilder(MAGNIA_SPROUTS).add(ALLURING_MAGNIA_SPROUT, REPULSIVE_MAGNIA_SPROUT);
        getOrCreateTagBuilder(MAGNIA_TOWER_REPLACEABLE).add(END_STONE, MIRESTONE, ALLURING_MAGNIA, REPULSIVE_MAGNIA);
        getOrCreateTagBuilder(MIRESTONE_BLOCKS).add(CHISELED_MIRESTONE, POLISHED_MIRESTONE_BUTTON, POLISHED_MIRESTONE_PRESSURE_PLATE);
        getOrCreateTagBuilder(MIRESTONE_BLOCKS).add(MIRESTONE, MIRESTONE_SLAB, MIRESTONE_STAIRS, MIRESTONE_WALL);
        getOrCreateTagBuilder(MIRESTONE_BLOCKS).add(MIRESTONE_BRICKS, MIRESTONE_BRICK_SLAB, MIRESTONE_BRICK_STAIRS, MIRESTONE_BRICK_WALL);
        getOrCreateTagBuilder(MIRESTONE_BLOCKS).add(POLISHED_MIRESTONE, POLISHED_MIRESTONE_SLAB, POLISHED_MIRESTONE_STAIRS, POLISHED_MIRESTONE_WALL);
        getOrCreateTagBuilder(MURUBLIGHT_BRICK_BLOCKS).add(MURUBLIGHT_BRICKS, MURUBLIGHT_BRICK_SLAB, MURUBLIGHT_BRICK_STAIRS, MURUBLIGHT_BRICK_WALL);
        getOrCreateTagBuilder(MURUBLIGHT_CHANTERELLE_MATURES_ON).add(CORRUPT_OVERGROWTH);
        getOrCreateTagBuilder(MURUBLIGHT_STEMS).add(MURUBLIGHT_STEM, STRIPPED_MURUBLIGHT_STEM, MURUBLIGHT_HYPHAE, STRIPPED_MURUBLIGHT_HYPHAE);
        getOrCreateTagBuilder(MURUBLIGHT_WOOD).forceAddTag(MURUBLIGHT_STEMS).add(MURUBLIGHT_PLANKS, MURUBLIGHT_SLAB, MURUBLIGHT_STAIRS, MURUBLIGHT_FENCE, MURUBLIGHT_FENCE_GATE, MURUBLIGHT_BUTTON, MURUBLIGHT_SIGN, MURUBLIGHT_HANGING_SIGN, MURUBLIGHT_WALL_SIGN, MURUBLIGHT_WALL_HANGING_SIGN);
        getOrCreateTagBuilder(CHANTERELLE_BRICK_BLOCKS).forceAddTag(CELESTIAL_BRICK_BLOCKS).forceAddTag(MURUBLIGHT_BRICK_BLOCKS);
        getOrCreateTagBuilder(CHANTERELLE_CAP_BLOCKS).add(CELESTIAL_CAP, MURUBLIGHT_CAP);
        getOrCreateTagBuilder(NEW_END_STONE_BLOCKS).add(CHISELED_END_STONE, POLISHED_END_STONE_BUTTON, POLISHED_END_STONE_PRESSURE_PLATE);
        getOrCreateTagBuilder(NEW_END_STONE_BLOCKS).add(END_STONE_SLAB, END_STONE_STAIRS, END_STONE_WALL);
        getOrCreateTagBuilder(NEW_END_STONE_BLOCKS).add(POLISHED_END_STONE, POLISHED_END_STONE_SLAB, POLISHED_END_STONE_STAIRS, POLISHED_END_STONE_WALL);
        getOrCreateTagBuilder(NEW_PURPUR_BLOCKS).add(PURPUR_WALL, CHISELED_PURPUR);
        getOrCreateTagBuilder(ORE_REPLACEABLE).add(END_STONE, MIRESTONE);
        getOrCreateTagBuilder(OVERGROWTH_BLOCKS).add(CELESTIAL_OVERGROWTH, CORRUPT_OVERGROWTH);
        getOrCreateTagBuilder(OVERHEATS_MAGNIA_SPROUTS).add(MAGMA_BLOCK);
        getOrCreateTagBuilder(PURPUR_TILE_BLOCKS).add(PURPUR_TILES, PURPUR_TILE_STAIRS, PURPUR_TILE_SLAB);
        getOrCreateTagBuilder(RUBBLEMITE_SPAWNABLE_ON).add(END_STONE, MIRESTONE, VERADITE, KURODITE, VEILED_END_STONE, CELESTIAL_OVERGROWTH, CORRUPT_OVERGROWTH, ALLURING_MAGNIA, REPULSIVE_MAGNIA);
        getOrCreateTagBuilder(RUSTLE_FOOD).add(MURUBLIGHT_CHANTERELLE);
        getOrCreateTagBuilder(RUSTLE_PREFERRED).add(VEILED_END_STONE);
        getOrCreateTagBuilder(RUSTLE_SPAWNABLE_ON).add(VEILED_END_STONE, END_STONE);
        getOrCreateTagBuilder(SHADOLINE_BLOCKS).add(CHISELED_SHADOLINE, SHADOLINE_PILLAR);
        getOrCreateTagBuilder(SHADOLINE_BLOCKS).add(CUT_SHADOLINE, CUT_SHADOLINE_SLAB, CUT_SHADOLINE_STAIRS, CUT_SHADOLINE_WALL);
        getOrCreateTagBuilder(SHADOLINE_BLOCKS).add(SHADOLINE_BLOCK, SHADOLINE_BLOCK_SLAB, SHADOLINE_BLOCK_STAIRS, SHADOLINE_BLOCK_WALL);
        getOrCreateTagBuilder(VEILED_LOGS).add(VEILED_LOG, STRIPPED_VEILED_LOG, VEILED_WOOD, STRIPPED_VEILED_WOOD);
        getOrCreateTagBuilder(VEILED_SAPLING_MATURES_ON).add(VEILED_END_STONE);
        getOrCreateTagBuilder(VEILED_WOODLANDS_VEGETATION_PLANTABLE_ON).add(END_STONE, VEILED_END_STONE, CELESTIAL_OVERGROWTH);
        getOrCreateTagBuilder(VEILED_WOOD_TAG).forceAddTag(VEILED_LOGS).add(VEILED_PLANKS, VEILED_SLAB, VEILED_STAIRS, VEILED_FENCE, VEILED_FENCE_GATE, VEILED_BUTTON, VEILED_SIGN, VEILED_HANGING_SIGN, VEILED_WALL_SIGN, VEILED_WALL_HANGING_SIGN);
        getOrCreateTagBuilder(VERADITE_BLOCKS).add(CHISELED_VERADITE, POLISHED_VERADITE_BUTTON, POLISHED_VERADITE_PRESSURE_PLATE);
        getOrCreateTagBuilder(VERADITE_BLOCKS).add(POLISHED_VERADITE, POLISHED_VERADITE_SLAB, POLISHED_VERADITE_STAIRS, POLISHED_VERADITE_WALL);
        getOrCreateTagBuilder(VERADITE_BLOCKS).add(VERADITE, VERADITE_SLAB, VERADITE_STAIRS, VERADITE_WALL);
        getOrCreateTagBuilder(VERADITE_BLOCKS).add(VERADITE_BRICKS, VERADITE_BRICK_SLAB, VERADITE_BRICK_STAIRS, VERADITE_BRICK_WALL);

        getOrCreateTagBuilder(BlockTags.MINEABLE_WITH_AXE)
                .forceAddTag(CELESTIAL_WOOD)
                .forceAddTag(MURUBLIGHT_WOOD)
                .forceAddTag(VEILED_WOOD_TAG)
                .add(VEILED_VINES, FLANGER_BERRY_VINE, BLINKLIGHT_VINES_BODY, BLINKLIGHT_VINES_HEAD);

        getOrCreateTagBuilder(BlockTags.MINEABLE_WITH_HOE)
                .forceAddTag(CHANTERELLE_CAP_BLOCKS)
                .add(VEILED_LEAF_PILE, RIPE_FLANGER_BERRY_BLOCK, UNRIPE_FLANGER_BERRY_BLOCK, FLANGER_BERRY_FLOWER, VEILED_LEAVES);

        getOrCreateTagBuilder(BlockTags.MINEABLE_WITH_PICKAXE)
                .forceAddTag(DUSK_PURPUR_BLOCKS)
                .forceAddTag(END_ORE_BLOCKS)
                .forceAddTag(ETCHED_MAGNIA_BLOCKS)
                .forceAddTag(MAGNIA_BLOCKS)
                .forceAddTag(MAGNIA_SPROUTS)
                .forceAddTag(MIRESTONE_BLOCKS)
                .forceAddTag(CHANTERELLE_BRICK_BLOCKS)
                .forceAddTag(NEW_END_STONE_BLOCKS)
                .forceAddTag(NEW_PURPUR_BLOCKS)
                .forceAddTag(OVERGROWTH_BLOCKS)
                .forceAddTag(PURPUR_TILE_BLOCKS)
                .forceAddTag(SHADOLINE_BLOCKS)
                .forceAddTag(VERADITE_BLOCKS)
                .forceAddTag(KURODITE_BLOCKS)
                .add(BLINKLAMP, BULB_LANTERN, CELESTIAL_PATH_BLOCK, CORRUPT_PATH_BLOCK, END_LAMP, NEBULITE_BLOCK, RAW_SHADOLINE_BLOCK, VEILED_END_STONE, VOID_SHALE);

        getOrCreateTagBuilder(BlockTags.DRAGON_IMMUNE)
                .add(END_STONE_BRICKS, END_STONE_BRICK_STAIRS, END_STONE_BRICK_SLAB, END_STONE_BRICK_WALL)
                .forceAddTag(END_ORE_BLOCKS)
                .forceAddTag(KURODITE_BLOCKS)
                .forceAddTag(MIRESTONE_BLOCKS)
                .forceAddTag(NEW_END_STONE_BLOCKS)
                .forceAddTag(SHADOLINE_BLOCKS)
                .forceAddTag(VERADITE_BLOCKS);

        getOrCreateTagBuilder(BlockTags.BEACON_BASE_BLOCKS).add(NEBULITE_BLOCK);
        getOrCreateTagBuilder(BlockTags.CEILING_HANGING_SIGNS).add(VEILED_HANGING_SIGN, CELESTIAL_HANGING_SIGN, MURUBLIGHT_HANGING_SIGN);
        getOrCreateTagBuilder(BlockTags.CLIMBABLE).add(BLINKLIGHT_VINES_BODY, BLINKLIGHT_VINES_HEAD, FLANGER_BERRY_VINE, MURUBLIGHT_SHELF, VEILED_VINES);
        getOrCreateTagBuilder(BlockTags.COMBINATION_STEP_SOUND_BLOCKS).add(VEILED_LEAF_PILE);
        getOrCreateTagBuilder(BlockTags.FALL_DAMAGE_RESETTING).add(VEILED_LEAF_PILE);
        getOrCreateTagBuilder(BlockTags.FEATURES_CANNOT_REPLACE).add(END_TRIAL_SPAWNER, END_VAULT);
        getOrCreateTagBuilder(BlockTags.FENCE_GATES).add(VEILED_FENCE_GATE, CELESTIAL_FENCE_GATE, MURUBLIGHT_FENCE_GATE);
        getOrCreateTagBuilder(BlockTags.FLOWERS).add(WISP_FLOWER);
        getOrCreateTagBuilder(BlockTags.FLOWER_POTS).add(POTTED_ALLURING_MAGNIA_SPROUT, POTTED_BLINKLIGHT, POTTED_BULB_FLOWER, POTTED_CELESTIAL_CHANTERELLE, POTTED_CELESTIAL_GROWTH, POTTED_CHORUS_SPROUTS, POTTED_CORRUPT_GROWTH, POTTED_MURUBLIGHT_CHANTERELLE, POTTED_REPULSIVE_MAGNIA_SPROUT, POTTED_DRY_END_GROWTH, POTTED_VEILED_SAPLING, POTTED_WISP_GROWTH);
        getOrCreateTagBuilder(BlockTags.LEAVES).add(VEILED_LEAVES);
        getOrCreateTagBuilder(BlockTags.LOGS_THAT_BURN).forceAddTag(VEILED_LOGS).forceAddTag(CELESTIAL_STEMS).forceAddTag(MURUBLIGHT_STEMS);
        getOrCreateTagBuilder(BlockTags.MUSHROOM_GROW_BLOCK).forceAddTag(OVERGROWTH_BLOCKS);
        getOrCreateTagBuilder(BlockTags.NEEDS_DIAMOND_TOOL).add(NEBULITE_ORE, MIRESTONE_NEBULITE_ORE, NEBULITE_BLOCK);
        getOrCreateTagBuilder(BlockTags.NEEDS_STONE_TOOL).add(SHADOLINE_ORE, MIRESTONE_SHADOLINE_ORE).forceAddTag(SHADOLINE_BLOCKS).forceAddTag(MAGNIA_BLOCKS).forceAddTag(MAGNIA_SPROUTS);
        getOrCreateTagBuilder(BlockTags.PLANKS).add(VEILED_PLANKS, CELESTIAL_PLANKS, MURUBLIGHT_PLANKS);
        getOrCreateTagBuilder(BlockTags.SMALL_FLOWERS).add(BULB_FLOWER);

        getOrCreateTagBuilder(BlockTags.SLABS).add(
                CELESTIAL_BRICK_SLAB,
                CELESTIAL_SLAB,
                DUSK_PURPUR_SLAB,
                END_STONE_SLAB,
                KURODITE_BRICK_SLAB,
                KURODITE_SLAB,
                MIRESTONE_BRICK_SLAB,
                MIRESTONE_SLAB,
                MURUBLIGHT_BRICK_SLAB,
                MURUBLIGHT_SLAB,
                POLISHED_END_STONE_SLAB,
                POLISHED_KURODITE_SLAB,
                POLISHED_MIRESTONE_SLAB,
                POLISHED_VERADITE_SLAB,
                PURPUR_TILE_SLAB,
                SHADOLINE_BLOCK_SLAB,
                CUT_SHADOLINE_SLAB,
                VEILED_SLAB,
                VERADITE_BRICK_SLAB,
                VERADITE_SLAB
        );

        getOrCreateTagBuilder(BlockTags.STAIRS).add(
                CELESTIAL_BRICK_STAIRS,
                CELESTIAL_STAIRS,
                DUSK_PURPUR_STAIRS,
                END_STONE_STAIRS,
                KURODITE_BRICK_STAIRS,
                KURODITE_STAIRS,
                MIRESTONE_BRICK_STAIRS,
                MIRESTONE_STAIRS,
                MURUBLIGHT_BRICK_STAIRS,
                MURUBLIGHT_STAIRS,
                POLISHED_END_STONE_STAIRS,
                POLISHED_KURODITE_STAIRS,
                POLISHED_MIRESTONE_STAIRS,
                POLISHED_VERADITE_STAIRS,
                PURPUR_TILE_STAIRS,
                SHADOLINE_BLOCK_STAIRS,
                CUT_SHADOLINE_STAIRS,
                VEILED_STAIRS,
                VERADITE_BRICK_STAIRS,
                VERADITE_STAIRS
        );

        getOrCreateTagBuilder(BlockTags.WALLS).add(
                CELESTIAL_BRICK_WALL,
                DUSK_PURPUR_WALL,
                END_STONE_WALL,
                KURODITE_BRICK_WALL,
                KURODITE_WALL,
                MIRESTONE_BRICK_WALL,
                MIRESTONE_WALL,
                MURUBLIGHT_BRICK_WALL,
                POLISHED_END_STONE_WALL,
                POLISHED_KURODITE_WALL,
                POLISHED_MIRESTONE_WALL,
                POLISHED_VERADITE_WALL,
                PURPUR_WALL,
                SHADOLINE_BLOCK_WALL,
                CUT_SHADOLINE_WALL,
                VERADITE_BRICK_WALL,
                VERADITE_WALL
        );

        getOrCreateTagBuilder(BlockTags.STANDING_SIGNS).add(VEILED_SIGN, CELESTIAL_SIGN, MURUBLIGHT_SIGN);
        getOrCreateTagBuilder(BlockTags.STONE_BUTTONS).add(POLISHED_END_STONE_BUTTON, POLISHED_MIRESTONE_BUTTON, POLISHED_VERADITE_BUTTON, POLISHED_KURODITE_BUTTON);
        getOrCreateTagBuilder(BlockTags.STONE_PRESSURE_PLATES).add(POLISHED_END_STONE_PRESSURE_PLATE, POLISHED_MIRESTONE_PRESSURE_PLATE, POLISHED_VERADITE_PRESSURE_PLATE, POLISHED_KURODITE_PRESSURE_PLATE);
        getOrCreateTagBuilder(BlockTags.WALL_HANGING_SIGNS).add(VEILED_WALL_HANGING_SIGN, CELESTIAL_WALL_HANGING_SIGN, MURUBLIGHT_WALL_HANGING_SIGN);
        getOrCreateTagBuilder(BlockTags.WALL_SIGNS).add(VEILED_WALL_SIGN, CELESTIAL_WALL_SIGN, MURUBLIGHT_WALL_SIGN);
        getOrCreateTagBuilder(BlockTags.WOODEN_BUTTONS).add(VEILED_BUTTON, CELESTIAL_BUTTON, MURUBLIGHT_BUTTON);
        getOrCreateTagBuilder(BlockTags.WOODEN_DOORS).add(VEILED_DOOR, CELESTIAL_DOOR, MURUBLIGHT_DOOR);
        getOrCreateTagBuilder(BlockTags.WOODEN_FENCES).add(VEILED_FENCE, CELESTIAL_FENCE, MURUBLIGHT_FENCE);
        getOrCreateTagBuilder(BlockTags.WOODEN_PRESSURE_PLATES).add(VEILED_PRESSURE_PLATE, CELESTIAL_PRESSURE_PLATE, MURUBLIGHT_PRESSURE_PLATE);
        getOrCreateTagBuilder(BlockTags.WOODEN_SLABS).add(VEILED_SLAB, CELESTIAL_SLAB, MURUBLIGHT_SLAB);
        getOrCreateTagBuilder(BlockTags.WOODEN_STAIRS).add(VEILED_STAIRS, CELESTIAL_STAIRS, MURUBLIGHT_STAIRS);
        getOrCreateTagBuilder(BlockTags.WOODEN_TRAPDOORS).add(VEILED_TRAPDOOR, CELESTIAL_TRAPDOOR, MURUBLIGHT_TRAPDOOR);

        getOrCreateTagBuilder(STRIPPED_LOGS).add(STRIPPED_VEILED_LOG, STRIPPED_CELESTIAL_STEM, STRIPPED_MURUBLIGHT_STEM);
        getOrCreateTagBuilder(STRIPPED_WOODS).add(STRIPPED_VEILED_WOOD, STRIPPED_CELESTIAL_HYPHAE, STRIPPED_MURUBLIGHT_HYPHAE);
        getOrCreateTagBuilder(ORES).add(NEBULITE_ORE, SHADOLINE_ORE, MIRESTONE_NEBULITE_ORE, MIRESTONE_SHADOLINE_ORE);
        getOrCreateTagBuilder(STORAGE_BLOCKS).add(SHADOLINE_BLOCK, NEBULITE_BLOCK, DRIFT_JELLY_BLOCK);

        getOrCreateTagBuilder(externalKey("antixray", "hidden_only_ores")).add(NEBULITE_ORE, MIRESTONE_NEBULITE_ORE);

        getOrCreateTagBuilder(externalKey("create", "tree_attachments")).add(MURUBLIGHT_SHELF);
        getOrCreateTagBuilder(externalKey("create", "tree_roots")).add(VEILED_LOG, VEILED_WOOD);
        getOrCreateTagBuilder(externalKey("create", "wrench_pickup")).add(BLINKLAMP, ALLURING_MAGNIA_SPROUT, REPULSIVE_MAGNIA_SPROUT);
    }

    private TagKey<Block> externalKey(String namespace, String path) {
        return TagKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(namespace, path));
    }
}